# Generated by Django 4.2.4 on 2023-08-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Reclama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'reclama',
            },
        ),
    ]
